
import { StyleSheet } from 'react-native';
import { widthPercentageToDP as wp, heightPercentageToDP as hp } from 'react-native-responsive-screen';
import { COLORS } from './Color';


const PRIMARY_COLOR = '#4CAD73';
const SECONDARY_COLOR = '#2E8B57';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8f9fa',
  },
  header: {
    overflow: 'hidden',
  },
  headerGradient: {
    paddingTop: hp('2%'),
    paddingBottom: hp('3%'),
    backgroundColor: COLORS.primary
  },
  headerContent: {
    paddingHorizontal: wp('5%'),
  },
  headerTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: hp('2%'),
  },
  locationContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  locationText: {
    marginLeft: hp('1%'),
    marginRight: wp('1%'),
  },
  deliverTo: {
    fontSize: wp('3%'),
    color: '#fff',
    opacity: 0.8,
  },
  locationName: {
    fontSize: wp('3.8%'),
    fontWeight: '600',
    color: '#fff',
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerButton: {
    width: wp('10%'),
    height: wp('10%'),
    borderRadius: wp('5%'),
    backgroundColor: 'rgba(255,255,255,0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: wp('3%'),
    position: 'relative',
  },
  notificationBadge: {
    position: 'absolute',
    top: -2,
    right: -2,
    backgroundColor: '#FF5252',
    borderRadius: wp('2%'),
    width: wp('4%'),
    height: wp('4%'),
    justifyContent: 'center',
    alignItems: 'center',
  },
  notificationBadgeText: {
    color: '#fff',
    fontSize: wp('2.2%'),
    fontWeight: 'bold',
  },
  cartBadge: {
    position: 'absolute',
    top: -2,
    right: -2,
    backgroundColor: '#FF9800',
    borderRadius: wp('2%'),
    width: wp('4%'),
    height: wp('4%'),
    justifyContent: 'center',
    alignItems: 'center',
  },
  cartBadgeText: {
    color: '#fff',
    fontSize: wp('2.2%'),
    fontWeight: 'bold',
  },
  welcomeText: {
    fontSize: wp('4.2%'),
    color: '#fff',
    opacity: 0.9,
    textAlign: 'center',
  },
  searchSection: {
    paddingHorizontal: wp('5%'),
    marginTop: -hp('2%'),
    marginBottom: hp('2%'),
    zIndex: 100,
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: wp('3%'),
    paddingHorizontal: wp('4%'),
    height: hp('6%'),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 5,
  },
  searchIcon: {
    marginRight: wp('3%'),
  },
  searchInput: {
    flex: 1,
    fontSize: wp('4%'),
    color: '#333',
  },
  filterButton: {
    padding: wp('2%'),
  },
  content: {
    flex: 1,
  },
  section: {
    marginBottom: hp('2%'),
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: wp('5%'),
    marginBottom: hp('2%'),
  },
  sectionTitle: {
    fontSize: wp('4.5%'),
    fontWeight: 'bold',
    color: '#333',
  },
  seeAllText: {
    fontSize: wp('3.5%'),
    color: PRIMARY_COLOR,
    fontWeight: '600',
  },
  offersContainer: {
    paddingHorizontal: wp('5%'),
  },
  offerCard: {
    width: wp('85%'),
    height: hp('22%'),
    marginRight: wp('4%'),
    borderRadius: wp('4%'),
    overflow: 'hidden',
    position: 'relative',
  },
  offerBackgroundImage: {
    width: '100%',
    height: '100%',
    position: 'absolute',
  },
  offerOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.3)',
    padding: wp('5%'),
    justifyContent: 'space-between',
  },
  offerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  discountCircle: {
    width: wp('15%'),
    height: wp('15%'),
    borderRadius: wp('7.5%'),
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  discountCircleText: {
    fontSize: wp('4%'),
    fontWeight: 'bold',
    color: PRIMARY_COLOR,
  },
  discountCircleSubtext: {
    fontSize: wp('2.5%'),
    fontWeight: '600',
    color: PRIMARY_COLOR,
  },
  validUntilContainer: {
    backgroundColor: 'rgba(255,255,255,0.9)',
    paddingHorizontal: wp('3%'),
    paddingVertical: hp('0.5%'),
    borderRadius: wp('3%'),
  },
  validUntilText: {
    fontSize: wp('3%'),
    color: '#333',
    fontWeight: '500',
  },
  offerContent: {
    alignItems: 'flex-start',
  },
  offerTitle: {
    fontSize: wp('5.5%'),
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: hp('0.5%'),
    textShadowColor: 'rgba(0,0,0,0.5)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  offerSubtitle: {
    fontSize: wp('4%'),
    color: '#fff',
    marginBottom: hp('0.5%'),
    textShadowColor: 'rgba(0,0,0,0.5)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  offerDescription: {
    fontSize: wp('3.2%'),
    color: '#fff',
    opacity: 0.9,
    marginBottom: hp('1.5%'),
    textShadowColor: 'rgba(0,0,0,0.5)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  offerButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.9)',
    paddingHorizontal: wp('4%'),
    paddingVertical: hp('1%'),
    borderRadius: wp('5%'),
  },
  offerButtonText: {
    color: '#333',
    fontSize: wp('3.5%'),
    fontWeight: '600',
    marginRight: wp('2%'),
  },
  quickActionsContainer: {
    paddingHorizontal: wp('5%'),
  },
  quickActionCard: {
    alignItems: 'center',
    marginRight: wp('6%'),
  },
  quickActionIcon: {
    width: wp('15%'),
    height: wp('15%'),
    borderRadius: wp('7.5%'),
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: hp('1%'),
  },
  quickActionText: {
    fontSize: wp('3.2%'),
    color: '#666',
    fontWeight: '500',
  },
  categoriesContainer: {
    paddingHorizontal: wp('5%'),
  },
  categoryCard: {
    width: hp('10%'),
    height: hp('10%'),
    marginRight: wp('4%'),
    borderRadius: hp(100),
    overflow: 'hidden',
  },
  categoryImage: {
    width: '100%',
    height: '100%',
    position: 'absolute',
    resizeMode:"contain"
  },
  categoryGradient: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center"
  },
  categoryIcon: {
    fontSize: wp('6%'),
    marginBottom: hp('0.5%'),
  },
  categoryName: {
    fontSize: wp('3.5%'),
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: hp('0.3%'),
  },
  categoryCount: {
    fontSize: wp('3%'),
    color: '#fff',
    opacity: 0.8,
  },
  newArrivalsContainer: {
    paddingHorizontal: wp('5%'),
  },
  newArrivalCard: {
    width: wp('35%'),
    backgroundColor: '#fff',
    borderRadius: wp('4%'),
    marginRight: wp('4%'),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
    marginBottom: hp(1)

  },
  newArrivalImageContainer: {
    width: '100%',
    height: hp('12%'),
    borderTopLeftRadius: wp('4%'),
    borderTopRightRadius: wp('4%'),
    overflow: 'hidden',
    position: 'relative',
  },
  newArrivalImage: {
    width: '100%',
    height: '100%',
  },
  newBadge: {
    position: 'absolute',
    top: wp('2%'),
    left: wp('2%'),
    backgroundColor: PRIMARY_COLOR,
    paddingHorizontal: wp('2%'),
    paddingVertical: hp('0.3%'),
    borderRadius: wp('2%'),
  },
  newBadgeText: {
    color: '#fff',
    fontSize: wp('2.5%'),
    fontWeight: 'bold',
  },
  newArrivalInfo: {
    padding: wp('3%'),
  },
  newArrivalCategory: {
    fontSize: wp('2.8%'),
    color: '#666',
    marginBottom: hp('0.3%'),
  },
  newArrivalName: {
    fontSize: wp('3.5%'),
    fontWeight: '600',
    color: '#333',
    marginBottom: hp('0.5%'),
  },
  newArrivalPrice: {
    fontSize: wp('3.8%'),
    fontWeight: 'bold',
    color: PRIMARY_COLOR,
  },
  weeklyDealsContainer: {
    paddingHorizontal: wp('5%'),
  },
  weeklyDealCard: {
    width: wp('60%'),
    height: hp('18%'),
    marginRight: wp('4%'),
    borderRadius: wp('4%'),
    overflow: 'hidden',
    position: 'relative',
  },
  weeklyDealImage: {
    width: '100%',
    height: '100%',
  },
  weeklyDealOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.4)',
    padding: wp('3%'),
    justifyContent: 'flex-end',
  },
  weeklyDealHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  weeklyDiscountBadge: {
    backgroundColor: '#FF3D00',
    paddingHorizontal: wp('2%'),
    paddingVertical: hp('0.3%'),
    borderRadius: wp('2%'),
  },
  weeklyDiscountText: {
    color: '#fff',
    fontSize: wp('2.8%'),
    fontWeight: 'bold',
  },
  daysLeftContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.2)',
    paddingHorizontal: wp('2%'),
    paddingVertical: hp('0.3%'),
    borderRadius: wp('2%'),
  },
  daysLeftText: {
    color: '#fff',
    fontSize: wp('2.5%'),
    marginLeft: wp('1%'),
  },
  weeklyDealInfo: {
    alignItems: 'flex-start',
  },
  weeklyDealName: {
    fontSize: wp('4%'),
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: hp('0.5%'),
  },
  weeklyPriceContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  weeklyCurrentPrice: {
    fontSize: wp('4.2%'),
    fontWeight: 'bold',
    color: '#fff',
    marginRight: wp('2%'),
  },
  weeklyOriginalPrice: {
    fontSize: wp('3.2%'),
    color: '#fff',
    opacity: 0.7,
    textDecorationLine: 'line-through',
  },
  productsContainer: {
    paddingHorizontal: wp('5%'),
  },
  productCard: {
    width: wp('40%'),
    backgroundColor: '#fff',
    borderRadius: wp('4%'),
    marginRight: wp('4%'),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
    marginBottom: hp(1)
  },
  productImageContainer: {
    width: '100%',
    height: hp('15%'),
    borderTopLeftRadius: wp('4%'),
    borderTopRightRadius: wp('4%'),
    overflow: 'hidden',
    position: 'relative',
  },
  productImage: {
    width: '100%',
    height: '100%',
  },
  discountBadge: {
    position: 'absolute',
    top: wp('2%'),
    left: wp('2%'),
    backgroundColor: '#FF3D00',
    paddingHorizontal: wp('2%'),
    paddingVertical: hp('0.3%'),
    borderRadius: wp('2%'),
  },
  discountText: {
    color: '#fff',
    fontSize: wp('2.5%'),
    fontWeight: 'bold',
  },
  outOfStockBadge: {
    position: 'absolute',
    top: wp('2%'),
    left: wp('2%'),
    backgroundColor: 'rgba(0,0,0,0.7)',
    paddingHorizontal: wp('2%'),
    paddingVertical: hp('0.3%'),
    borderRadius: wp('2%'),
  },
  outOfStockText: {
    color: '#fff',
    fontSize: wp('2.5%'),
    fontWeight: 'bold',
  },
  favoriteButton: {
    position: 'absolute',
    top: wp('2%'),
    right: wp('2%'),
    width: wp('8%'),
    height: wp('8%'),
    borderRadius: wp('4%'),
    backgroundColor: 'rgba(0,0,0,0.3)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  productInfo: {
    padding: wp('3%'),
  },
  productName: {
    fontSize: wp('3.5%'),
    fontWeight: '600',
    color: '#333',
    marginBottom: hp('0.3%'),
  },
  productUnit: {
    fontSize: wp('3%'),
    color: '#666',
    marginBottom: hp('0.5%'),
  },
  ratingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: hp('0.8%'),
  },
  ratingText: {
    fontSize: wp('3%'),
    color: '#666',
    marginLeft: wp('1%'),
  },
  priceContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: hp('1%'),
  },
  currentPrice: {
    fontSize: wp('4%'),
    fontWeight: 'bold',
    color: PRIMARY_COLOR,
    marginRight: wp('2%'),
  },
  originalPrice: {
    fontSize: wp('3.2%'),
    color: '#999',
    textDecorationLine: 'line-through',
  },
  addButton: {
    width: wp('8%'),
    height: wp('8%'),
    borderRadius: wp('4%'),
    backgroundColor: '#F0F9F4',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'flex-end',
    borderWidth: 1,
    borderColor: '#E0E0E0',
  },
  addButtonDisabled: {
    backgroundColor: '#f5f5f5',
    borderColor: '#e0e0e0',
  },
  storeInfoSection: {
    paddingHorizontal: wp('5%'),
    marginBottom: hp('3%'),
  },
  storeInfoCard: {
    backgroundColor: '#fff',
    borderRadius: wp('4%'),
    padding: wp('5%'),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
  },
  storeInfoHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: hp('2%'),
  },
  storeInfoTitle: {
    fontSize: wp('4.5%'),
    fontWeight: 'bold',
    color: '#333',
    marginLeft: wp('3%'),
  },
  storeInfoItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: hp('1.2%'),
  },
  storeInfoText: {
    fontSize: wp('3.5%'),
    color: '#666',
    marginLeft: wp('3%'),
  },
  directionsButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F0F9F4',
    paddingVertical: hp('1.5%'),
    borderRadius: wp('3%'),
    marginTop: hp('1%'),
  },
  directionsButtonText: {
    fontSize: wp('3.8%'),
    color: PRIMARY_COLOR,
    fontWeight: '600',
    marginRight: wp('2%'),
  },
  featuresSection: {
    paddingHorizontal: wp('5%'),
    marginBottom: hp('3%'),
  },
  featuresGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginTop: hp('2%'),
  },
  featureItem: {
    width: wp('42%'),
    backgroundColor: '#fff',
    borderRadius: wp('4%'),
    padding: wp('4%'),
    alignItems: 'center',
    marginBottom: hp('2%'),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
  },
  featureIcon: {
    width: wp('12%'),
    height: wp('12%'),
    borderRadius: wp('6%'),
    backgroundColor: '#F0F9F4',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: hp('1%'),
  },
  featureTitle: {
    fontSize: wp('3.8%'),
    fontWeight: '600',
    color: '#333',
    marginBottom: hp('0.5%'),
    textAlign: 'center',
  },
  featureText: {
    fontSize: wp('3%'),
    color: '#666',
    textAlign: 'center',
    lineHeight: hp('2%'),
  },
  footer: {
    backgroundColor: '#fff',
    marginTop: hp('2%'),
    paddingTop: hp('4%'),
    borderTopWidth: 1,
    borderTopColor: '#f0f0f0',
  },
  footerContent: {
    paddingHorizontal: wp('5%'),
  },
  footerLogo: {
    alignItems: 'center',
    marginBottom: hp('3%'),
  },
  logoContainer: {
    width: wp('15%'),
    height: wp('15%'),
    borderRadius: wp('7.5%'),
    backgroundColor: '#F0F9F4',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: hp('1%'),
  },
  footerAppName: {
    fontSize: wp('5%'),
    fontWeight: 'bold',
    color: '#333',
    marginBottom: hp('0.5%'),
  },
  footerTagline: {
    fontSize: wp('3.5%'),
    color: '#666',
    textAlign: 'center',
  },
  footerLinks: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: hp('3%'),
  },
  footerColumn: {
    alignItems: 'center',
  },
  footerColumnTitle: {
    fontSize: wp('4%'),
    fontWeight: '600',
    color: '#333',
    marginBottom: hp('1%'),
  },
  footerLink: {
    marginBottom: hp('0.8%'),
  },
  footerLinkText: {
    fontSize: wp('3.2%'),
    color: '#666',
  },
  socialMedia: {
    alignItems: 'center',
    marginBottom: hp('2%'),
  },
  socialIcons: {
    flexDirection: 'row',
    justifyContent: 'center',
  },
  socialIcon: {
    width: wp('10%'),
    height: wp('10%'),
    borderRadius: wp('5%'),
    backgroundColor: '#f8f9fa',
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: wp('2%'),
  },
  footerBottom: {
    borderTopWidth: 1,
    borderTopColor: '#f0f0f0',
    paddingVertical: hp('2%'),
    paddingHorizontal: wp('5%'),
    alignItems: 'center',
  },
  copyrightText: {
    fontSize: wp('3%'),
    color: '#999',
    marginBottom: hp('0.5%'),
  },
  versionText: {
    fontSize: wp('2.8%'),
    color: '#ccc',
  },
  bottomSpacing: {
    height: hp('2%'),
  },
});