import { StyleSheet } from "react-native";
import { widthPercentageToDP as wp, heightPercentageToDP as hp } from 'react-native-responsive-screen';
import { COLORS } from '../Color';


export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8F9FA',
  },
  keyboardAvoidView: {
    flex: 1,
  },
  scrollContainer: {
    flexGrow: 1,
  },
  headerSection: {
    height: hp('35%'),
    position: 'relative',
    overflow: 'hidden',
    backgroundColor: COLORS.primary
  },
  backButton: {
    position: 'absolute',
    top: hp(3),

    left: wp('5%'),
    zIndex: 10,
    padding: wp('2%'),
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: wp('60%'),
  },
  headerContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: wp('5%'),
  },
  logoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: hp('3%'),
  },
  logoIconContainer: {
    width: wp('12%'),
    height: wp('12%'),
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderRadius: wp('6%'),
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: wp('3%'),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  logoEmoji: {
    fontSize: wp('7%'),
  },
  logoText: {
    fontSize: wp('6.5%'),
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  welcomeContainer: {
    alignItems: 'center',
  },
  welcomeText: {
    fontSize: wp('8%'),
    fontWeight: 'bold',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: hp('1%'),
  },
  subtitleText: {
    fontSize: wp('4%'),
    color: 'rgba(255, 255, 255, 0.9)',
    textAlign: 'center',
    lineHeight: wp('5.5%'),
  },
  decorativeContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: -1,
  },
  decorativeCircle1: {
    position: 'absolute',
    width: wp('40%'),
    height: wp('40%'),
    borderRadius: wp('20%'),
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    top: -wp('10%'),
    right: -wp('15%'),
  },
  decorativeCircle2: {
    position: 'absolute',
    width: wp('25%'),
    height: wp('25%'),
    borderRadius: wp('12.5%'),
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    bottom: wp('5%'),
    left: -wp('8%'),
  },
  decorativeCircle3: {
    position: 'absolute',
    width: wp('15%'),
    height: wp('15%'),
    borderRadius: wp('7.5%'),
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
    top: wp('15%'),
    left: wp('10%'),
  },
  formCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    marginTop: -hp('3%'),
    borderTopLeftRadius: wp('8%'),
    borderTopRightRadius: wp('8%'),
    paddingHorizontal: wp('6%'),
    paddingTop: hp('4%'),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
  },
  formHeader: {
    alignItems: 'center',
    marginBottom: hp('4%'),
  },
  formTitle: {
    fontSize: wp('7%'),
    fontWeight: 'bold',
    color: '#2C3E50',
    marginBottom: hp('1%'),
  },
  formSubtitle: {
    fontSize: wp('3.8%'),
    color: '#7F8C8D',
    textAlign: 'center',
    lineHeight: wp('5%'),
  },
  inputContainer: {
    marginBottom: hp('2.5%'),
  },
  inputLabel: {
    fontSize: wp('4%'),
    color: '#2C3E50',
    marginBottom: hp('1%'),
    fontWeight: '600',
    paddingLeft: wp('1%'),
  },
  textInputContainer: {
    backgroundColor: '#F8F9FA',
    borderRadius: wp('4%'),
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#E9ECEF',
 
  },
  inputFocused: {
    borderColor: COLORS.primary,
    backgroundColor: 'rgba(46, 125, 50, 0.03)',
  },
  inputIconContainer: {
    paddingLeft: wp('4%'),
    paddingRight: wp('2%'),
  },
  textInput: {
    flex: 1,
    paddingVertical: hp('2.2%'),
    fontSize: wp('4%'),
    color: '#2C3E50',
  },
  eyeIcon: {
    padding: wp('3%'),
  },
  forgotPasswordContainer: {
    alignSelf: 'flex-end',
    marginBottom: hp('3%'),
  },
  forgotPasswordText: {
    color: COLORS.primary,
    fontSize: wp('3.8%'),
    fontWeight: '600',
  },
  loginButton: {
    borderRadius: wp('4%'),
    marginBottom: hp('3%'),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 4,
  },
  loginButtonGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: hp('2.2%'),
    borderRadius: wp('4%'),
  },
  loginButtonText: {
    color: '#FFFFFF',
    fontSize: wp('4.5%'),
    fontWeight: '600',
    marginRight: wp('2%'),
  },
  loginButtonIcon: {
    marginLeft: wp('1%'),
  },
  dividerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: hp('3%'),
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#E9ECEF',
  },
  dividerText: {
    marginHorizontal: wp('4%'),
    color: '#7F8C8D',
    fontSize: wp('3.5%'),
    fontWeight: '500',
  },
  socialButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: hp('3%'),
  },
  socialButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F8F9FA',
    paddingVertical: hp('2%'),
    borderRadius: wp('4%'),
    marginHorizontal: wp('1%'),
    borderWidth: 1,
    borderColor: '#E9ECEF',
  },
  socialIconContainer: {
    width: wp('8%'),
    height: wp('8%'),
    borderRadius: wp('4%'),
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: wp('2%'),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
  },
  socialIconImage: {
    width: wp('5%'),
    height: wp('5%'),
  },
  socialButtonText: {
    fontSize: wp('4%'),
    fontWeight: '500',
    color: '#2C3E50',
  },
  registerContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: hp('3%'),
  },
  registerText: {
    color: '#7F8C8D',
    fontSize: wp('4%'),
  },
  registerLink: {
    color: COLORS.primary,
    fontSize: wp('4%'),
    fontWeight: 'bold',
  },
});