
import { StyleSheet } from 'react-native';
import { widthPercentageToDP as wp, heightPercentageToDP as hp } from 'react-native-responsive-screen';
import { COLORS } from '../Color';

const PRIMARY_COLOR = '#4CAD73';
const SECONDARY_COLOR = '#2E8B57';


export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8f9fa',
  },
  header: {
    paddingTop: hp('2%'),
    paddingBottom: hp('2%'),
    backgroundColor: COLORS.primary
  },
  headerContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: wp('5%'),
  },
  backButton: {
    width: wp('10%'),
    height: wp('10%'),
    borderRadius: wp('5%'),
    backgroundColor: 'rgba(255,255,255,0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: wp('5%'),
    fontWeight: 'bold',
    color: '#fff',
    flex: 1,
    textAlign: 'center',
  },
  headerRight: {
    width: wp('10%'),
  },
  cartBadge: {
    backgroundColor: '#fff',
    borderRadius: wp('3%'),
    paddingHorizontal: wp('2%'),
    paddingVertical: hp('0.5%'),
    minWidth: wp('6%'),
    alignItems: 'center',
  },
  cartBadgeText: {
    color: PRIMARY_COLOR,
    fontSize: wp('3.5%'),
    fontWeight: 'bold',
  },
  content: {
    flex: 1,
  },
  pickupInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    margin: wp('4%'),
    padding: wp('4%'),
    borderRadius: wp('3%'),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
  },
  pickupIconContainer: {
    width: wp('10%'),
    height: wp('10%'),
    borderRadius: wp('5%'),
    backgroundColor: '#F0F9F4',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: wp('3%'),
  },
  pickupText: {
    flex: 1,
  },
  pickupTitle: {
    fontSize: wp('4%'),
    fontWeight: '600',
    color: '#333',
    marginBottom: hp('0.3%'),
  },
  pickupSubtitle: {
    fontSize: wp('3.2%'),
    color: '#666',
  },
  pickupBadge: {
    backgroundColor: PRIMARY_COLOR,
    paddingHorizontal: wp('3%'),
    paddingVertical: hp('0.5%'),
    borderRadius: wp('4%'),
  },
  pickupBadgeText: {
    color: '#fff',
    fontSize: wp('3%'),
    fontWeight: 'bold',
  },
  readyTimeCard: {
    backgroundColor: '#fff',
    marginHorizontal: wp('4%'),
    marginBottom: wp('4%'),
    padding: wp('4%'),
    borderRadius: wp('3%'),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
    alignItems: 'center',
    marginTop: hp(3)
  },
  readyTimeHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: hp('1%'),
  },
  readyTimeTitle: {
    fontSize: wp('4%'),
    fontWeight: '600',
    color: '#333',
    marginLeft: wp('2%'),
  },
  readyTimeValue: {
    fontSize: wp('6%'),
    fontWeight: 'bold',
    color: PRIMARY_COLOR,
    marginBottom: hp('0.5%'),
  },
  readyTimeNote: {
    fontSize: wp('3.2%'),
    color: '#666',
    textAlign: 'center',
  },
  timeSelectionCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#fff',
    marginHorizontal: wp('4%'),
    marginBottom: wp('4%'),
    padding: wp('4%'),
    borderRadius: wp('3%'),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
  },
  timeSelectionLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  timeSelectionText: {
    marginLeft: wp('3%'),
  },
  timeSelectionTitle: {
    fontSize: wp('3.8%'),
    fontWeight: '600',
    color: '#333',
    marginBottom: hp('0.3%'),
  },
  timeSelectionValue: {
    fontSize: wp('3.5%'),
    color: PRIMARY_COLOR,
    fontWeight: '500',
  },
  cartSection: {
    backgroundColor: '#fff',
    marginHorizontal: wp('4%'),
    marginBottom: wp('4%'),
    borderRadius: wp('3%'),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: wp('4%'),
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  sectionTitle: {
    fontSize: wp('4.2%'),
    fontWeight: 'bold',
    color: '#333',
  },
  itemCount: {
    fontSize: wp('3.5%'),
    color: '#666',
  },
  cartItem: {
    flexDirection: 'row',
    padding: wp('4%'),
    borderBottomWidth: 1,
    borderBottomColor: '#f8f9fa',
  },
  cartItemDisabled: {
    opacity: 0.6,
  },
  itemImageContainer: {
    width: wp('20%'),
    height: wp('20%'),
    borderRadius: wp('2%'),
    overflow: 'hidden',
    marginRight: wp('3%'),
    position: 'relative',
  },
  itemImage: {
    width: '100%',
    height: '100%',
  },
  discountBadge: {
    position: 'absolute',
    top: wp('1%'),
    right: wp('1%'),
    backgroundColor: '#FF3D00',
    paddingHorizontal: wp('1.5%'),
    paddingVertical: hp('0.3%'),
    borderRadius: wp('1%'),
  },
  discountText: {
    color: '#fff',
    fontSize: wp('2.2%'),
    fontWeight: 'bold',
  },
  outOfStockOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  outOfStockText: {
    color: '#fff',
    fontSize: wp('2.5%'),
    fontWeight: 'bold',
  },
  itemDetails: {
    flex: 1,
  },
  itemHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: hp('0.5%'),
  },
  itemName: {
    fontSize: wp('3.8%'),
    fontWeight: '600',
    color: '#333',
    flex: 1,
    marginRight: wp('2%'),
  },
  itemNameDisabled: {
    color: '#999',
  },
  removeButton: {
    padding: wp('1%'),
  },
  itemMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: hp('0.8%'),
  },
  itemCategory: {
    fontSize: wp('3%'),
    color: '#666',
  },
  availabilityBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: wp('2%'),
    paddingVertical: hp('0.3%'),
    borderRadius: wp('3%'),
  },
  availabilityDot: {
    width: wp('2%'),
    height: wp('2%'),
    borderRadius: wp('1%'),
    marginRight: wp('1%'),
  },
  availabilityText: {
    fontSize: wp('2.8%'),
    fontWeight: '500',
  },
  priceContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: hp('1%'),
  },
  currentPrice: {
    fontSize: wp('4%'),
    fontWeight: 'bold',
    color: PRIMARY_COLOR,
    marginRight: wp('2%'),
  },
  priceDisabled: {
    color: '#999',
  },
  originalPrice: {
    fontSize: wp('3.2%'),
    color: '#999',
    textDecorationLine: 'line-through',
    marginRight: wp('2%'),
  },
  unit: {
    fontSize: wp('3%'),
    color: '#666',
  },
  itemFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  prepTimeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  prepTime: {
    fontSize: wp('3%'),
    color: '#666',
    marginLeft: wp('1%'),
  },
  quantityContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  quantityButton: {
    width: wp('8%'),
    height: wp('8%'),
    borderRadius: wp('4%'),
    backgroundColor: '#F0F9F4',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E0E0E0',
  },
  quantityButtonDisabled: {
    backgroundColor: '#f5f5f5',
    borderColor: '#e0e0e0',
  },
  quantityText: {
    fontSize: wp('4%'),
    fontWeight: '600',
    color: '#333',
    marginHorizontal: wp('4%'),
    minWidth: wp('8%'),
    textAlign: 'center',
  },
  summarySection: {
    backgroundColor: '#fff',
    marginHorizontal: wp('4%'),
    marginBottom: wp('4%'),
    padding: wp('4%'),
    borderRadius: wp('3%'),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: hp('1%'),
  },
  summaryLabel: {
    fontSize: wp('3.5%'),
    color: '#666',
  },
  summaryValue: {
    fontSize: wp('3.5%'),
    color: '#333',
    fontWeight: '500',
  },
  savingsLabel: {
    color: PRIMARY_COLOR,
  },
  savingsValue: {
    color: PRIMARY_COLOR,
    fontWeight: '600',
  },
  freeText: {
    color: PRIMARY_COLOR,
    fontWeight: '600',
  },
  divider: {
    height: 1,
    backgroundColor: '#e0e0e0',
    marginVertical: hp('1.5%'),
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: hp('1%'),
  },
  totalLabel: {
    fontSize: wp('4.2%'),
    fontWeight: 'bold',
    color: '#333',
  },
  totalValue: {
    fontSize: wp('4.5%'),
    fontWeight: 'bold',
    color: PRIMARY_COLOR,
  },
  paymentNote: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: '#F0F9F4',
    padding: wp('3%'),
    borderRadius: wp('2%'),
    marginTop: hp('1%'),
  },
  paymentNoteText: {
    fontSize: wp('3.2%'),
    color: '#666',
    marginLeft: wp('2%'),
    flex: 1,
    lineHeight: hp('2%'),
  },
  notesSection: {
    backgroundColor: '#fff',
    marginHorizontal: wp('4%'),
    marginBottom: wp('4%'),
    padding: wp('4%'),
    borderRadius: wp('3%'),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
  },
  noteItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginTop: hp('1%'),
  },
  noteText: {
    fontSize: wp('3.2%'),
    color: '#666',
    marginLeft: wp('2%'),
    flex: 1,
    lineHeight: hp('2%'),
  },
  reserveContainer: {
    backgroundColor: '#fff',
    paddingHorizontal: wp('4%'),
    paddingVertical: hp('1.5%'),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 10,
  },
  reserveButton: {
    borderRadius: wp('3%'),
    overflow: 'hidden',
  },
  reserveButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: wp('5%'),
    paddingVertical: hp('2%'),
  },
  reserveLeft: {
    alignItems: 'flex-start',
  },
  reserveTotal: {
    fontSize: wp('5%'),
    fontWeight: 'bold',
    color: '#fff',
  },
  reserveItems: {
    fontSize: wp('3.2%'),
    color: '#fff',
    opacity: 0.9,
  },
  reserveRight: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  reserveText: {
    fontSize: wp('4%'),
    fontWeight: '600',
    color: '#fff',
    marginRight: wp('2%'),
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#fff',
    borderTopLeftRadius: wp('5%'),
    borderTopRightRadius: wp('5%'),
    paddingBottom: hp('3%'),
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: wp('5%'),
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  modalTitle: {
    fontSize: wp('4.5%'),
    fontWeight: 'bold',
    color: '#333',
  },
  timeSlotOption: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: wp('5%'),
    paddingVertical: hp('2%'),
    borderBottomWidth: 1,
    borderBottomColor: '#f8f9fa',
  },
  timeSlotSelected: {
    backgroundColor: '#F0F9F4',
  },
  timeSlotDisabled: {
    opacity: 0.5,
  },
  timeSlotInfo: {
    flex: 1,
  },
  timeSlotTime: {
    fontSize: wp('4%'),
    fontWeight: '600',
    color: '#333',
    marginBottom: hp('0.3%'),
  },
  timeSlotTimeSelected: {
    color: PRIMARY_COLOR,
  },
  timeSlotTimeDisabled: {
    color: '#999',
  },
  timeSlotLabel: {
    fontSize: wp('3.2%'),
    color: '#666',
  },
  timeSlotLabelSelected: {
    color: PRIMARY_COLOR,
  },
  timeSlotLabelDisabled: {
    color: '#999',
  },
  unavailableText: {
    fontSize: wp('3%'),
    color: '#999',
    fontStyle: 'italic',
  },
  emptyCart: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: wp('10%'),
  },
  emptyCartImage: {
    width: wp('40%'),
    height: wp('40%'),
    marginBottom: hp('3%'),
    opacity: 0.7,
  },
  emptyCartTitle: {
    fontSize: wp('5%'),
    fontWeight: 'bold',
    color: '#333',
    marginBottom: hp('1%'),
  },
  emptyCartText: {
    fontSize: wp('3.8%'),
    color: '#666',
    textAlign: 'center',
    marginBottom: hp('3%'),
    lineHeight: hp('2.5%'),
  },
  shopNowButton: {
    backgroundColor: PRIMARY_COLOR,
    paddingHorizontal: wp('8%'),
    paddingVertical: hp('1.5%'),
    borderRadius: wp('6%'),
  },
  shopNowText: {
    color: '#fff',
    fontSize: wp('4%'),
    fontWeight: '600',
  },
  bottomSpacing: {
    height: hp('2%'),
  },
});